### ISSUE TITLE
proposal re: WordPress.com hiding settings

### ISSUE THREAD

**Issue by andypiper** [mckinnon/simple-fediverse-creator#1]
I came over to the repo to report that I had to set the Admin UI to the "Classic Style" in order to enable the settings for this plugin - but of course, you already included this in the README! :-)

The problem there is that the information is not available to see directly in the plugin catalog on WordPress.org or .com.

Suggestion: either put that section from the README into the description / info visible in the plugin catalog (I think many WP.com users are likely not to see it, otherwise); or, consider pulling the settings into their own menu that can be found in the sidebar - this is what plugins such as the IndieWeb plugin have done, for example.

Thanks for the plugin, this is really neat!

**Comment by andypiper** [comment]
Hmm, now I notice that the information *is* in the plugin catalog but it is under Installation, and I never clicked on that tab from WP.com as that is "done for me" in the sense that I just need to click to install in the dashboard. So again I guess it is more of a discoverability thing (or, I should be a smarter user). Hmm!

**Comment by mckinnon** [comment]
> Suggestion: either put that section from the README into the description / info visible in the plugin catalog (I think many WP.com users are likely not to see it, otherwise); or, consider pulling the settings into their own menu that can be found in the sidebar - this is what plugins such as the IndieWeb plugin have done, for example.

The presentation with the Installation tab is how the WP store formats README markup. I could add a note in the Description to check the Installation notes though. That's not a bad idea.

I made a conscious decision not to add new Admin menus for _Simple fediverse:creator_ and _Simple Mastodon Verification_ because they're intended to be as "simple" as possible. There's never going to be a full page of settings so adding a new page for just two fields is frivolous. The bug with WP.com's custom Admin interface was reported later and I haven't dug in enough to find a good alternative.

Thanks for the feedback. I'm glad you're getting some use from it.
